---
# tasks file for ansible-role-gui
- name: Install packages
  become: true
  package:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ packages }}"

- name: Clone xbanish
  git:
    clone: true
    repo: "{{ xbanish_url }}"
    dest: /tmp/xbanish

- name: Install xbanish
  become: true
  shell: make
  args:
    chdir: /tmp/xbanish
    warn: false
